url: https://test-stand.gb.ru/gateway/login
address: https://test-stand.gb.ru/api/posts

login: your_login
password: your_password

# Добавляем информацию для создания нового поста
new_post:
  title: "Название вашего нового поста"
  description: "Описание вашего нового поста"
  content: "Содержание вашего нового поста"
